# Referencia:
# https://docs.techdox.nz/mkdocs/

version: '3'
services:
  mkdocs:
    image: docker.io/squidfunk/mkdocs-material
    # image: squidfunk/mkdocs-material
    ports:
      - "8005:8000"
    volumes:
      - ./:/docs
    stdin_open: true
    tty: true