site_name: PythonDocs


theme:
  name: material
  # logo: assets/image.png
  # favicon: assets/image.png
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    # - python
    # - bash
  language: en
  # Modos para la pagina
  palette:
  
    # Modo automatico 
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode
    # Modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Cambia al modo oscuro
      primary: indigo
      # primary: custom
      accent: purple
    # Modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Cambia al modo claro
      primary: indigo
      # primary: custom
      accent: lime
  icon:
    annotation: material/arrow-right-circle
  features:
    - header.autohide
    - navigation.footer
    - content.code.copy
    - content.code.select
    - content.code.annotate
    # - search
    # - search.suggest
    # - search.highlight
    # - search.share
    # - search:
    #   lang: es

repo_url: https://github.com/MarceloMarot/PythonDocs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html

  - pymdownx.tasklist:
      custom_checkbox: true







extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets\extra.css

# extra:
#   version:
#     provider: mike
# extra:
#   consent:
#     actions:
#       - accept
#       - manage

# plugins:
#   - meta

nav:
  - Indice: index.md
  - Basicos:
    - contenido/1-comenzando.md
    - contenido/2-variables_asignaciones.md
    - contenido/3-expresiones_operadores.md
    - contenido/4-tipos_datos.md
    - contenido/5-control_flujo.md
    - contenido/6-funciones.md
    - contenido/7-modulos-paquetes.md
    - contenido/8-entorno_virtual.md
    - contenido/9-fechas.md
    - contenido/10-manejo_archivos.md
    - contenido/11-excepciones.md
    - contenido/12-clases.md
    - contenido/13-decoradores_abstracciones.md
    - contenido/14-SOLID.md
    - contenido/15-programacion_funcional.md
    - contenido/16-regex.md
    - contenido/sistema_operativo.md
    - contenido/archivos_temporales.md
    - contenido/enlaces.md
  - Modulos: 
    - modulos/pathlib.md
    - modulos/sys.md
  - Paquetes:
    - paquetes/python-i18n.md
    - paquetes/psutil.md
    - paquetes/numba.md
    - paquetes/ffmpeg.md
  # - Test: test.md
