site_name: PythonDocs


theme:
  name: material
  logo: assets/image.png
  # favicon: assets/image.png
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - python
    - bash
  language: en
  # Modos para la pagina
  palette:
  
    # Modo automatico 
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode
    # Modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Cambia al modo oscuro
    # Modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Cambia al modo claro

  features:
    - header.autohide
    - navigation.footer
    # - search
    # - search.suggest
    # - search.highlight
    # - search.share
    # - search:
    #   lang: es

repo_url: https://github.com/MarceloMarot/PythonDocs


# extra:
#   version:
#     provider: mike


# plugins:
#   - meta

nav:
  - Indice: index.md
  - Basicos:
    - contenido/1-comenzando.md
    - contenido/2-variables_asignaciones.md
    - contenido/3-expresiones_operadores.md
    - contenido/4-tipos_datos.md
    - contenido/5-control_flujo.md
    - contenido/6-funciones.md
    - contenido/7-modulos-paquetes.md
    - contenido/8-entorno_virtual.md
    - contenido/9-fechas.md
    - contenido/10-manejo_archivos.md
    - contenido/11-excepciones.md
    - contenido/12-clases.md
    - contenido/13-decoradores_abstracciones.md
    - contenido/14-SOLID.md
    - contenido/15-programacion_funcional.md
    - contenido/16-regex.md
    - contenido/sistema_operativo.md
    - contenido/archivos_temporales.md
    - contenido/enlaces.md
  - Modulos: 
    - modulos/pathlib.md
    - modulos/sys.md
  - Paquetes:
    - paquetes/python-i18n.md
    - paquetes/psutil.md
    - paquetes/numba.md
    - paquetes/ffmpeg.md

