site_name: PythonDocs


theme:
  name: material
  # name: mkdocs
  # name: readthedocs

  icon: 
    # logo: fontawesome/solid/user-nurse
    annotation: material/arrow-right-circle
    logo: simple/python  # :simple-python:


  # logo: assets/image.png
  # favicon: assets/image.png
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - python
    - bash
  language: es
  # Modos para la pagina
  palette:
  
    # Modo automatico 
    # - media: "(prefers-color-scheme)"
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode
    # Modo claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Cambia al modo oscuro
      primary: indigo
      # primary: custom
      accent: purple
    # Modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Cambia al modo claro
      primary: indigo
      # primary: custom
      accent: lime
  # icon:
    # annotation: material/arrow-right-circle

  features:
    - header.autohide
    - navigation.footer
    # - navigation.instant
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - search
    - search.suggest
    - search.highlight
    # - search.share
    # - search:
    #   lang: es

repo_url: https://github.com/MarceloMarot/PythonDocs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html

  - pymdownx.tasklist:
      custom_checkbox: true







extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets\extra.css

# extra:
#   version:
#     provider: mike
# extra:
#   consent:
#     actions:
#       - accept
#       - manage

# plugins:
#   - meta

nav:
  - Indice: index.md
  - Basicos:
    - Comenzando con Python: contenido/1-comenzando.md
    - Variables y Asignaciones: contenido/2-variables_asignaciones.md
    - Expresiones y Operadores: contenido/3-expresiones_operadores.md
    - Tipos de Datos: contenido/4-tipos_datos.md
    - Control de Flujo: contenido/5-control_flujo.md
    - Funciones: contenido/6-funciones.md
    - Módulos y Paquetes: contenido/7-modulos-paquetes.md
    - Entorno virtual - módulo VENV: contenido/8-entorno_virtual.md
    - Fechas y Horario: contenido/9-fechas.md
    - Manejo de Archivos: contenido/10-manejo_archivos.md
    - Errores y Excepciones: contenido/11-excepciones.md
    - Programacion Funcional: contenido/15-programacion_funcional.md
    - Decoradores: contenido/decoradores.md

    - Clases I - Definicion y Propiedades: contenido/12-clases.md
    - Clases II - Decoradores, Abstracciones y Métodos Especiales: contenido/13-decoradores_abstracciones.md
    - Clases III - Principios SOLID: contenido/14-SOLID.md
    
    - Paralelismo - Procesos: contenido/procesos.md
    - Paralelismo - Hilos: contenido/hilos.md
    - Paralelismo - Intercambio: contenido/intercambio.md

    - Enlaces: contenido/enlaces.md
  
  - Modulos: 
    - Pathlib - Manejo de rutas : modulos/pathlib.md
    - Sys - Parámetros y funciones del sistema: modulos/sys.md
    - Os - Comandos del Sistema Operativo: modulos/os.md
    - Tempfile - Archivos Temporales: modulos/tempfile.md
    - Re - Expresiones Regulares (RegEx): modulos/regex.md
    - Asyncio - Ejecución Asincrónica: modulos/asyncio.md
    - Logging - Reportes de errores: modulos/logging.md


  - Paquetes:
    - Archivos YAML - PyYAML: paquetes/pyyaml.md
    - Traducciones - python-i18n : paquetes/python-i18n.md
    - Psutil - Monitoreo del sistema: paquetes/psutil.md
    - Numba - Optimizacion con Machine Learning: paquetes/numba.md
    - FFMPEG-Python: paquetes/ffmpeg.md




